### ISSUE TITLE
Horas/fechas de docs en humano

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/madison#96]
![screen shot 2015-01-26 at 11 03 16 am](https://cloud.githubusercontent.com/assets/6226604/5904060/56152872-a54b-11e4-8a01-129eff7a9351.png)

**Comment by rodowi** [comment]
¿Cómo dicen las fechas los humanos?

**Comment by rodowi** [comment]
el filter date no está funcionando en la vista de documentos (En el controlador ReaderController) ya que las fechas no llegan en ISO8601

```json
{
    "id": 2,
    "title": "Logistic Regression",
    "slug": "logistic-regression",
    "shortname": null,
    "init_section": 3,
    "created_at": "2015-01-14 03:27:04",
    "updated_at": "2015-01-14 03:27:04",
    "deleted_at": null,
    "statuses": [],
    "user_sponsor": [],
    "categories": [],
    "dates": []
}
```

y en el HomeController sí:

```json
{
    "id": 2,
    "title": "Logistic Regression",
    "slug": "logistic-regression",
    "shortname": null,
    "init_section": 3,
    "created_at": "2015-01-14T03:27:04+00:00",
    "updated_at": "2015-01-14T03:27:04+00:00",
    "deleted_at": null,
    "categories": [],
    "statuses": [],
    "dates": []
}
```

**Comment by rodowi** [comment]
La línea que sospecho hace el cambio es https://github.com/mxabierto/madison/blob/master/app/controllers/DocumentApiController.php#L76, en getDocs(). 

Si trato de hacer parseo ISO8601 en https://github.com/mxabierto/madison/blob/master/app/controllers/DocumentApiController.php#L16, me arroja de error:

```
[2015-02-14 02:01:45] production.ERROR: exception 'InvalidArgumentException' with message 'Unexpected data found.
Trailing data' in /vagrant/vendor/nesbot/carbon/src/Carbon/Carbon.php:385
Stack trace:
#0 /vagrant/bootstrap/compiled.php(6785): Carbon\Carbon::createFromFormat('Y-m-d H:i:s', '2015-01-14T03:2...')
#1 /vagrant/bootstrap/compiled.php(6761): Illuminate\Database\Eloquent\Model->fromDateTime('2015-01-14T03:2...')
#2 /vagrant/bootstrap/compiled.php(6914): Illuminate\Database\Eloquent\Model->setAttribute('updated_at', '2015-01-14T03:2...')
```

**Comment by rodowi** [comment]
Según la doc de https://docs.angularjs.org/api/ng/filter/date

Necesitamos "seconds since epoch".
